name: Python Versions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: |
          python my_script.py > output.txt

      - name: Save output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Python ${{ matrix.python-version }} Output
          path: output.txt
